motos/chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_chat, name='new'),
]

motos/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

motos/item/urls.py
from django.urls import path
from . import views as vw_itm

app_name = 'item'

urlpatterns = [
    path('', vw_itm.items, name='items'),
    path('new/', vw_itm.NewItem, name='new_item'),
    path('<int:pk>/', vw_itm.detail, name='detail'),
    path('<int:pk>/delete/', vw_itm.DeleteItem, name='delete'),
    path('<int:pk>/edit/', vw_itm.EditItem, name='edit'),
]

motos/motors/urls.py
from django.urls import path
from . import views as vw_mtr
from django.contrib.auth import views as vw_auth
from .forms import LoginForm

app_name ='motors'

urlpatterns = [
    path('', vw_mtr.index, name='index'),
    path('contact/', vw_mtr.contact, name='contact'),
    path('singup/', vw_mtr.singup, name='singup'),
    path('login/', vw_auth.LoginView.as_view(template_name='motors/login.html', authentication_form=LoginForm), name='login')
]

motos/motos/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include

#Importo para que aparezcan las imagenes
#NOTA: No es recomendable hacerlo en produccion
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('motors.urls')),
    path('items/', include('item.urls')),
    path('dashboard', include('dashboard.urls')),
    path('inbox/', include('chat.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)#NOTA: No es recomendable hacerlo en produccion

motos/motors/models.py
from django.db import models

# Create your models here.

motos/motors/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User 

#(Crea un usuario)
class SingupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder' : 'Your name',
        'class' : 'w-full py-4 px-6 rounded-xl'
    }))
    
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder' : 'Your email',
        'class' : 'w-full py-4 px-6 rounded-xl'
    }))
    
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder' : 'Your password',
        'class' : 'w-full py-4 px-6 rounded-xl'
    }))
    
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder' : 'Cofirm your password',
        'class' : 'w-full py-4 px-6 rounded-xl'
    }))
    
#(Autentica y loguea un usuario)
class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder' : 'Your name',
        'class' : 'w-full py-4 px-6 rounded-xl'
    }))
    
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder' : 'Your password',
        'class' : 'w-full py-4 px-6 rounded-xl'
    }))

motos/motors/views.py
from django.shortcuts import redirect, render
# Create your views here.

from item.models import Category, Item
from .forms import SingupForm

#Items Views
def index(req):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()
    return render(req, 'motors/index.html', {
        'categories' : categories,
        'items' : items,
    })

#Contact Views
def contact(req):
    return render(req, 'motors/contact.html')

#Form Sing Up Views
def singup(req):
    
    if req.method == 'POST':
        form = SingupForm(req.POST)
        
        if form.is_valid():
            form.save()
            return redirect('/login/')
    else:
        form = SingupForm
    
    return render(req, 'motors/singup.html', {
        'form' : form
    })

motos/motors/templates/motors/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<script src="https://cdn.tailwindcss.com"></script>
    <title>Welcome To | {% block title %} {% endblock %}</title>
</head>
<body>
  
    <!--Navbar Start-->
    <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
      <a href="/" class="text-xl font-semibold">Full Motors</a>
      <div class="space-x-6">
        <a href="{% url 'item:new_item' %}" class="text-lg font-semibold hover:text-gray-500">New Item</a>
        <a href="{% url 'item:items' %}" class="text-lg font-semibold hover:text-gray-500">Browse</a>

        <!-- 1:14:50 -->
        {% if request.user.is_authenticated %}<!--Experiment request, o de no es req-->
          <a href="{% url 'chat:inbox' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Inbox</a>
          <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboar</a>
        {% else %} 
          <a href="{% url 'motors:singup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sing up</a>
          <a href="{% url 'motors:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a>
        {% endif %}

      </div>
    </nav><!--Navbar End-->

    <!--Main (Page content) Start-->
    <main class="px-6 py-6">
        {% block content %}
        {% endblock content %}
    </main><!--Main End-->
    
    <!--Footer Start-->
    <footer class="py-6 px-6 flex justify-between bg-gray-800">
      <div class="w-2/3 pr-10">
        <h3 class="mb-5 font-semibold text-gray-400">About</h3>
        <p class="text-lg text-gray-500">Lorem ipsu bla bla bla. Lorem ipsu bla bla bla. 
          Lorem ipsu bla bla bla. Lorem ipsu bla bla bla. 
        </p>
      </div>
      <div class="w-1/3">
        <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>
        <ul class="space-y-2">
          <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
          <li><a href="{% url 'motors:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li><!--href="motors:contact"-->
          <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy policy</a></li>
          <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Term of use</a></li>
        </ul>
      </div>
    </footer><!--Footer End-->

</body>
</html>

motos/motors/templates/motors/contact.html
{% extends "motors/base.html" %}

{% block title %}Contact{% endblock %}

{% block content %}
    <h1>Pagina de Contacto</h1>
{% endblock content %}

motos/motors/templates/motors/index.html
{% extends "motors/base.html" %}

{% block title %}Home{% endblock %}


{% block content %}
    <!--Items Start-->
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Newest items</h2>
        <div class="grid grid-cols-3 gap-6">
            {% for item in items %}
                <div class="flex flex-col">
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url }}" class="rounded-t-xl">
                        </div>
                        <div class="p-3 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">Price: {{ item.price }}$</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div><!--Items End-->

    <!--Categories options Start-->
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Category</h2>
        <div class="grid grid-cols-3 gap-6">
            {% for category in categories %}
                <div class="flex flex-col">
                    <a href="#">
                        <div class="p-3 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ category.name }}</h2>
                            <p class="text-gray-500">{{ category.items.count }} items</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div><!--Categories options End-->

{% endblock content %}

motos/motors/templates/motors/login.html
{% extends "motors/base.html" %}

{% block title %}Sing up{% endblock title %}

{% block content %}
    <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">Log in</h1>
        <form method="post" action=".">
            {% csrf_token %}

            <div class="mb-3">
                <label class="inline-block mb-2">Username</label><br>
                {{ form.username }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Password</label><br>
                {{ form.password }}
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}
                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Go</button>
        </form>
    </div>
{% endblock content %}

motos/motors/templates/motors/singup.html
{% extends "motors/base.html" %}

{% block title %}Sing up{% endblock title %}

{% block content %}
    <div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">Sing up</h1>
        <form method="post" action=".">
            {% csrf_token %}

            <div class="mb-3">
                <label class="inline-block mb-2">Username</label><br>
                {{ form.username }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Email</label><br>
                {{ form.email }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Password</label><br>
                {{ form.password1 }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2">Repeat password</label><br>
                {{ form.password2 }}
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}
                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Go</button>
        </form>
    </div>
{% endblock content %}