motos/chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_chat, name='new'),
]

motos/item/urls.py
from django.urls import path
from . import views as vw_itm

app_name = 'item'

urlpatterns = [
    path('', vw_itm.items, name='items'),
    path('new/', vw_itm.NewItem, name='new_item'),
    path('<int:pk>/', vw_itm.detail, name='detail'),
    path('<int:pk>/delete/', vw_itm.DeleteItem, name='delete'),
    path('<int:pk>/edit/', vw_itm.EditItem, name='edit'),
]

motos/motos/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include

#Importo para que aparezcan las imagenes
#NOTA: No es recomendable hacerlo en produccion
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('motors.urls')),
    path('items/', include('item.urls')),
    path('dashboard', include('dashboard.urls')),
    path('inbox/', include('chat.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)#NOTA: No es recomendable hacerlo en produccion

motos/item/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)
    
    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'
        
    def __str__(self):
        return self.name
    
class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.name

motos/item/forms.py
from django import forms
from .models import Item


INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'

#Crea un item
class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        #Minute Video 1:16:47
        fields = ('category', 'name', 'description', 'image', 'price', 'is_sold')
        widgets = {
            'category': forms.Select(attrs={
                'class' : INPUT_CLASSES
            }),
            'name': forms.TextInput(attrs={
                'class' : INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class' : INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class' : INPUT_CLASSES
            })
        }

#Edita un item
class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        #Minute Video 1:37:20
        fields = ('name', 'description', 'image', 'price')
        widgets = {
            'name': forms.TextInput(attrs={
                'class' : INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class' : INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class' : INPUT_CLASSES
            })
        }

motos/item/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.decorators import login_required

#Importamos "Q" esto hace que sea mas facil buscar en multiples campos
from django.db.models import Q
from .models import Category, Item
from .forms import EditItemForm, NewItemForm

# Create your views here.

def items(req):
    #Obtiene todos los articulos de la DB que se venden
    query = req.GET.get('query', '')
    category_id = req.GET.get('category', 0)
    categories = Category.objects.all()
    items = Item.objects.filter(is_sold=False)
    
    if category_id:
        items = items.filter(category_id=category_id)
    
    if query:
        items = items.filter(Q(name__icontains=query) | Q(description__icontains=query))
    
    return render(req, 'item/items.html', {
        'items': items,
        'query': query,
        'categories': categories,
        'category_id': int(category_id),
    })

def detail(req, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)[0:3]
    return render(req, 'item/detail.html', {
        'item' : item,
        'related_items': related_items
    })
    
@login_required
#Si desea intentar visitar esto (sin estar autenticado) sera redirigido a la pagina de inicio de sesion
def NewItem(req):
    if req.method == 'POST':
        form = NewItemForm(req.POST, req.FILES)      
        #1:25:41
        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = req.user
            item.save()
            
            return redirect('item:detail', pk=item.id)
    else:
        form = NewItemForm() #Instancia la class NewItemForm
    
    return render(req, 'item/form.html', {
        'form': form,
        'title': 'New Item',
    })

@login_required
#Si desea intentar visitar esto (sin estar autenticado) sera redirigido a la pagina de inicio de sesion
#Edita un item
def EditItem(req, pk):
    item = get_object_or_404(Item, pk=pk, created_by=req.user)
    if req.method == 'POST':
        form = EditItemForm(req.POST, req.FILES, instance=item)
        
        if form.is_valid():
            item.save()
            
            return redirect('item:detail', pk=item.id)
    else:
        form = EditItemForm(instance=item) #Instancia la class NewItemForm
    
    return render(req, 'item/form.html', {
        'form': form,
        'title': 'Edit Item',
    })


#Funcion para eliminar un item
@login_required
def DeleteItem(req, pk):
    item = get_object_or_404(Item, pk=pk, created_by=req.user)
    item.delete()
    
    return redirect('dashboard:index')

motos/item/templates/item/detail.html
{% extends "motors/base.html" %}

{% block title %} {{item.name}} {% endblock title %}

<!--Page content Start-->
{% block content %}
    
    <div class="grid grid-cols-5 gap-6">
        <!--Item Image Details Start-->
        <div class="col-span-3">
            <img src="{{ item.image.url }}" class="rounded-xl">
        </div><!--Item Image Details End-->

        <!--Details Start-->
        <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
            <h1 class="mb-6 text-3xl">{{ item.name }}</h1>
            <p class="text-gray-500"><strong>Price: </strong>{{ item.price }}$</p>
            <p class="text-gray-500"><strong>Seller: </strong>{{ item.created_by.username }}</p>
            
            {% if item.description %}
                <p class="text-gray-700">
                    <strong class="text-gray-500">Description:</strong><br>
                    {{ item.description }}
                </p>
            {% endif %}
            
            {% if request.user == item.created_by %}
                <div class="mt-6 p-6 bg-white rounded-xl">
                    <p>This is your item!</p>
                    <a href="{% url 'item:edit' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl">Edit</a>
                    <a href="{% url 'item:delete' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">Delete</a>
                </div>
            {% else %}
                <a href="{% url 'chat:new' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Contact seller</a>
            {% endif %}
        </div><!--Details End-->
    </div>

    <!--Items Related Start-->
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Related items</h2>
        <div class="grid grid-cols-3 gap-6">
            {% for item in related_items %}
                <div class="flex flex-col">
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url }}" class="rounded-t-xl">
                        </div>
                        <div class="p-3 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">Price: {{ item.price }}$</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div><!--Items Related End-->

{% endblock  %}<!--Page content End-->

motos/item/templates/item/form.html
{% extends "motors/base.html" %}

{% block title %} {{ title }} {% endblock title %}

{% block content %}
<h1 class="mb-6 text-3xl">{{ title }}</h1>
<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}<!--Lo usamos para evitar inyecciones SQL (averiguar bien de que se trata)-->
    <div class="space-y-4">
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}
            {{ form.non_field_errors }}
        </div>
    {% endif %}
    <button class="mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Save</button>
</form>
{% endblock content %}

motos/item/templates/item/items.html
{% extends "motors/base.html" %}

{% block title %}Browse Intem{% endblock title %}

{% block content %}
    <div class="pb-6 grid grid-cols-4 gap-4 bg-gray-100 p-3 rounded-xl">
        <div class="col-span-1">
            <!--Search Start-->
            <form method="get" action="{% url 'item:items' %}">
                <input name="query" class="w-full py-4 px-6 border rounded-xl" type="text" value="{{ query }}" placeholder="Find a bike, a chair or car...">
                <button class="mt-2 py-4 px-8 text-lg bg-teal-500 text-white rounded-xl">Search</button>
            </form><!--Search End-->

            <!--Select Category Start-->
            <hr class="my-6">
            <p class="font-semibold">Categories</p>
            <ul>
                {% for category in categories%}
                    <li class="py-2 px-2 rounded-xl{% if category.id == category_id %} bg-gray-200 {% endif %}">
                        <!--1:49:21-->
                        <a href="{% url 'item:items' %}?query={{ query }}&category={{ category.id }}">{{ category.name }}</a>
                    </i>
                {% endfor %}
            </ul>
            <!--Select Category End-->

            <hr class="my-6">
            <p class="font-semibold">Clear filters</p>
            <ul>
                <li><a href="{% url "item:items" %}" class="mt-2 py-4 px-8 inline-block bg-yellow-500 text-lg rounded-xl text-white">Clear</a></li>
            </ul>

        </div>
        <div class="col-span-3">
            <div class="grid grid-cols-3 gap-6">
                {% for item in items %}
                    <div class="flex flex-col">
                        <a href="{% url 'item:detail' item.id %}">
                            <div>
                                <img src="{{ item.image.url }}" class="rounded-t-xl">
                            </div>
                            <div class="p-3 bg-white rounded-b-xl">
                                <h2 class="text-2xl">{{ item.name }}</h2>
                                <p class="text-gray-500">Price: {{ item.price }}$</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}